name: Wake Minecraft Server

on:
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Minecraft server through Pico
        run: |
          curl -v --max-time 15 \
            "http://${{ secrets.WOL_PICO_IP }}:54322/wake/${{ secrets.WOL_PICO_TOKEN }}"
